new: true

type: scalar

# Short text description of the data you are providing.
description: "The AQI is an index for reporting daily air quality. It tells you how clean or polluted your air is, and what associated health effects might be a concern for you. The AQI focuses on health effects you may experience within a few hours or days after breathing polluted air. EPA calculates the AQI for five major air pollutants regulated by the Clean Air Act: ground-level ozone, particle pollution (also known as particulate matter), carbon monoxide, sulfur dioxide, and nitrogen dioxide. For each of these pollutants, EPA has established national air quality standards to protect public health .Ground-level ozone and airborne particles are the two pollutants that pose the greatest threat to human health in this country."

poweredBy: '<a href="http://www.airnow.gov/"><img src="http://www.enviroflash.info/assets/logos/cityLogo-0-0.gif"/></a>'

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: UTC

# URL sourceUrls are provided by the initialization function for this River.
#sourceUrls:

# How often should River View poll your data sourceUrls?
interval: 1 hour

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 6 months

# Primary data, usually collected in one location. Should both be scalar values.
fields:
- Particle Pollution (2.5 microns)
- Particle Pollution (10 microns)
- Ozone

# This provides more information about the data. This data doesn't change over
# time like the fields.
metadata:
- agency
- location

# These are excluded RSS ids that don't return anything.
excludedFeeds:
- 71
- 75
- 102
- 96
- 244
- 246
- 290
- 303
- 300
- 302
- 306
- 304
- 346
- 343
- 454
- 472
- 510
- 509
- 513
- 515
- 516
- 534
- 511
- 535
- 577
- 543
- 587
- 602
- 605
- 616
- 621
- 620
- 626
- 625
- 633
- 634
- 643
- 653
- 730
- 732
- 738
- 758
- 760
- 761
- 155
- 212
- 206
- 254
- 263
- 261
- 249
- 251
- 262
- 248
- 258
- 260
- 257
- 255
- 256
- 259
- 488
- 489
- 487
- 493
- 492
- 506
- 508
- 541
- 507
- 549
- 551
- 560
- 550
- 563
- 562
- 725
- 564
- 566
- 723
- 724
- 565
- 726
- 547
- 247
- 266
- 265
- 234
- 232
- 229
- 224
- 225
- 216
- 195
- 192
- 194
- 193
- 190
- 185
- 141
- 449
- 451
- 525
- 524
- 522
- 514
- 512
