type: scalar

description: Missouri water levels provided by National Weather Service.

poweredBy: '<a href="http://water.weather.gov/ahps/"><img src="http://water.weather.gov/resources/images/noaaleft.jpg"></a>'

author: Matthew Taylor
email: matt@numenta.org

timezone: America/Chicago

sourceUrls:
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=trym7&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=trym8&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=grfi2&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=clkm7&output=xml"
  - "http://water.weather.gov/ahps2/hydrograph_to_xml.php?gage=sclm7&output=xml"

interval: 15 minutes

expires: 6 months

fields:
  - Stage
  - Flow

metadata:
  - originator
  - name
  - id
  - generationtime
