type: scalar

# Short text description of the data you are providing.
description: Maryland traffic speeds for key roadways. Lifted from http://www.chart.state.md.us/rss/rssfeeds.asp.

poweredBy: '<a href="http://www.chart.state.md.us/"><img src="http://www.chart.state.md.us/egov/img/agencyLogo-generic.png"></a>'

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: America/New_York

# A list of URLs that contain the raw data. Each of these will be polled at the
# interval specified below, and the response text will be sent to your parser.
sourceUrls:
  - http://www.chart.state.md.us/rss/ProduceRSS.aspx?Type=TravelSpeedsXML&filter=ALL

# How often should River View poll your data sourceUrls?
interval: 10 minutes

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 6 months

# Primary data, usually collected in one location. Should both be scalar values.
fields:
  - minSpeed
  - maxSpeed

# This provides more information about the data. This data doesn't change over
# time like the fields.
metadata:
  - devideID
  - location
  - latitude
  - longitude
  - direction
