type: scalar

# Short text description of the data you are providing.
description: City of Chicago Beach Water Quality - Automated Sensors - 2015 - Water Temperature. See https://data.cityofchicago.org/Parks-Recreation/Beach-Water-Quality-Automated-Sensors-2015-Water-T/3ipq-j3gd/about.

poweredBy: '<a href="https://data.cityofchicago.org/"><img src="https://data.cityofchicago.org/stylesheets/images/domains/data.cityofchicago.org/chicago_logo.png"></a>'

author: Matthew Taylor
email: matt@numenta.org

# Timezone is important! You should use the timezone that the data is
# collected, or if time of day does not matter in the data patterns, you many
# use "UTC"
timezone: America/Chicago

soda:
- source: data.cityofchicago.org
  dataset: 3ipq-j3gd
  limit: 100

# How often should River View poll your data sourceUrls?
interval: 1 hour

# When should your collected data expire? This means that River View will store
# a time-boxed window of data. Data outside of this timebox will be flushed.
expires: 6 months

# Primary data, usually collected in one location. Should both be scalar values.
fields:
- water_temperature # Water temperature in Celsius degrees.
- turbidity         # Water turbidity in Nephelometric Turbidity Units (NTU)
- wave_height       # Wave height in meters.
- wave_period       # Wave period in seconds.

# This provides more information about the data. This data doesn't change over
# time like the fields.
metadata:
- beach_name
- battery_life
- last_updated_label
